---
kind: pipeline
name: client-python-tests

steps:
  - name: client-test
    image: python:3.9
    commands:
      - pip3 install -r requirements.txt --user
      - pip3 install -r test-requirements.txt --user
      - python3 -m pytest --no-header -vv --disable-warnings --connectors --drone

services:
  - name: redis
    image: redis:7.0.4
  - name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms2g -Xmx2g
  - name: minio
    image: minio/minio:RELEASE.2022-08-26T19-53-15Z
    environment:
      MINIO_ROOT_USER: ChangeMe
      MINIO_ROOT_PASSWORD: ChangeMe
      command: [ server, /data ]
