---
version: 2.1

jobs:
  ensure_formatting:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: install test-dependencies
          command: pip3 install -r test-requirements.txt --user
      - run:
          name: confirm black version
          command: black --version
      - run:
          name: run black check
          command: black --check .
  linter:
    docker:
      - image: alpine/flake8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: flake8
          command: flake8 --ignore=E,W ~/repo
  tests:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: install test-dependencies
          command: pip3 install -r test-requirements.txt --user
      - run:
          name: run pytest
          command: python3 -m pytest --cov=pycti
  build:
    working_directory: ~/opencti-client
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: build
          command: python3 setup.py sdist bdist_wheel
      - persist_to_workspace:
          root: ~/opencti-client
          paths:
            - dist
  deploy:
    working_directory: ~/opencti-client
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: ~/opencti-client
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt --user
      - run:
          name: verify git tag vs. version
          command: python3 setup.py verify
      - run:
          name: install twine
          command: sudo pip3 install twine
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = opencti" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: twine upload dist/*

workflows:
  version: 2
  opencti_client_python:
    jobs:
      - ensure_formatting:
          filters:
            tags:
              only: /.*/    
      - linter:
          filters:
            tags:
              only: /.*/    
      - tests:
          filters:
            tags:
              only: /.*/
          version: "3.9"
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - ensure_formatting
            - linter
            - tests
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)([a-z]?)*/
            branches:
              ignore: /.*/
