name: "Check PR"

on:
  push:
    branches:
      - master
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master

jobs:
  check-fork:
    name: CheckFork
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check fork data
        run: echo ${{github.event.pull_request.head.repo.full_name}}